In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv('flipkart_products.csv')

In [12]:
df.sample(5)

,Product Name,Price,Discription,Rating,Page Number
840,"Tecno Spark Go 3 (Titanium Grey, 64 GB)","₹12,499",4 GB RAM | 64 GB ROM17.12 cm (6.74 inch) HD+ D...,4.1,36
452,"ARMobile Screen Guard for 9H Surface Hardness,...",₹133,Scratch ResistantMobileScreen Guard,NaN,19
109,"I Kall Z20 Plus Smartphone – 6.26"" Display, Su...","₹6,499",6 GB RAM | 128 GB ROM | Expandable Upto 256 GB...,3.3,5
324,"Snexian Bold T150 (Purple, 16 GB)","₹7,373",2 GB RAM | 16 GB ROM7.62 cm (3 inch) Display5M...,3.2,14
285,"IQOO Z11x 5G (Titan Black, 256 GB)","₹33,851",8 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Displ...,4.3,12

In [25]:
df.shape

(984, 5)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  984 non-null    object
 1   Price         975 non-null    object
 2   Discription   983 non-null    object
 3   Rating        921 non-null    float64
 4   Page Number   984 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 38.6+ KB

In [ ]:
# Changing the datatype of Price column from object to float after removing the ₹ symbol and commas

df['Price'] = df['Price'].str.replace('₹', '').str.replace(',', '').astype(float)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  984 non-null    object
 1   Price         975 non-null    float64
 2   Discription   983 non-null    object
 3   Rating        921 non-null    float64
 4   Page Number   984 non-null    int64
dtypes: float64(2), int64(1), object(2)
memory usage: 38.6+ KB

In [27]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Price,975.0,24418.155897,23311.686516,106.0,8995.0,17999.0,33248.5,189999.0
Rating,921.0,4.150489,0.359048,2.3,4.1,4.2,4.4,5.0
Page Number,984.0,21.000000,11.838176,1.0,11.0,21.0,31.0,41.0

In [33]:
df[df['Price'] < 1000].sort_values(by='Price', ascending=False).head(10)

,Product Name,Price,Discription,Rating,Page Number
611,Jio Bharat V4 4G,999.0,32 MB RAM | 32 MB ROM | Expandable Upto 128 MB...,3.6,26
470,GFive Touch,999.0,32 MB RAM | 32 MB ROM7.11 cm (2.8 inch) NA Dis...,3.1,20
480,GFive Touch,999.0,32 MB RAM | 32 MB ROM7.11 cm (2.8 inch) NA Dis...,3.1,21
561,CASE CREATION Screen Guard for Apple Iphone 8+,799.0,"Air-bubble Proof, UV Protection, Anti Fingerpr...",NaN,24
585,CASE CREATION Screen Guard for Apple Iphone 8 ...,499.0,"Air-bubble Proof, UV Protection, Anti Fingerpr...",NaN,25
562,MAHIV RUDRANSH Screen Guard for IIPHONE 14 PRO,428.0,"Scratch Resistant, Anti Bacterial, Air-bubble ...",NaN,24
328,Stir Collections Screen Guard for All Smartphone,399.0,Anti BacterialMobileScreen Guard,NaN,14
582,GENTECK Screen Guard for Screen Protector for ...,366.0,"Air-bubble Proof, Anti Fingerprint, Anti Bacte...",NaN,25
514,CASE CREATION Tempered Glass Guard for Apple i...,299.0,"Air-bubble Proof, Smart Screen Guard, Washable...",NaN,22
549,Mokteck Screen Guard for Screen Protector for ...,298.0,"Air-bubble Proof, Anti Bacterial, Anti Glare, ...",NaN,23